changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"
  - "**/*.story.{js,ts,tsx}"
  - "**/*.stories.{js,ts,tsx}"
  - javascript/webapp/**/*

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      '@types/react': { optional: true }
  "@fluentui/react-hooks@*":
    peerDependenciesMeta:
      '@types/react': { optional: true }
  "@fluentui/react@*":
    peerDependenciesMeta:
      '@types/react': { optional: true }
      '@types/react-dom': { optional: true }
      'react-dom': { optional: true }
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@monaco-editor/react@*":
    peerDependenciesMeta:
      "react-dom": { optional: true }
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      "webpack": "*"
    peerDependenciesMeta:
      "@babel/core": { optional: true }
      "webpack": { optional: true }
  "@storybook/addons@*":
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
  "@storybook/store@*":
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
    peerDependenciesMeta:
      '@babel/core': { optional: true }
  "@storybook/core-common@*":
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
  path-equal@*:
    dependencies:
      tslib: "*"
  styled-components@*:
    dependencies:
      react-is: ^16
    peerDependenciesMeta:
      react-dom: { optional: true }
  "@devtools-ds/themes@*":
    peerDependencies:
      "react-dom": "*"
    peerDependenciesMeta:
      "react-dom": { optional: true }
  allotment@*:
    peerDependenciesMeta:
      react-dom: { optional: true }
  observable-hooks@*:
    peerDependenciesMeta:
      react-dom: { optional: true }
  react-router-dom@*:
    peerDependenciesMeta:
      react-dom: { optional: true }
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
