changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"
  - "**/*.story.{js,ts,tsx}"
  - "**/*.stories.{js,ts,tsx}"
  - javascript/webapp/**/*

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@fluentui/utilities@*":
    peerDependenciesMeta:
      "@types/react": { optional: true }
  "@fluentui/react-hooks@*":
    peerDependenciesMeta:
      "@types/react": { optional: true }
  "@fluentui/react@*":
    peerDependenciesMeta:
      "@types/react": { optional: true }
      "@types/react-dom": { optional: true }
      "react-dom": { optional: true }
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@monaco-editor/react@*":
    peerDependenciesMeta:
      "react-dom": { optional: true }
  "@storybook/addon-docs@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      "@babel/core": "*"
      "webpack": "*"
    peerDependenciesMeta:
      "@babel/core": { optional: true }
      "webpack": { optional: true }
  "@storybook/addons@*":
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
  "@storybook/store@*":
    peerDependenciesMeta:
      react: { optional: true }
      react-dom: { optional: true }
  path-equal@*:
    dependencies:
      tslib: "*"
  styled-components@*:
    dependencies:
      react-is: ^16
    peerDependenciesMeta:
      react-dom: { optional: true }
  allotment@*:
    peerDependenciesMeta:
      react-dom: { optional: true }
  observable-hooks@*:
    peerDependenciesMeta:
      react-dom: { optional: true }
  react-router-dom@*:
    peerDependenciesMeta:
      react-dom: { optional: true }
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      "webpack": "*"
    peerDependenciesMeta:
      "@storybook/react-webpack5":
        optional: true
      "webpack":
        optional: true
      react-dom:
        optional: true
  "@storybook/addon-interactions@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
      "webpack": "*"
  "@storybook/addon-controls@*":
    peerDependencies:
      "webpack": "*"
      "@storybook/react-webpack5": "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "@storybook/react-webpack5": "*"
  "@storybook/core-common@*":
    dependencies:
      "glob": "^7"
    peerDependencies:
      "@storybook/react-webpack5": "*"
      "webpack": ">= 5"
    peerDependenciesMeta:
      "@storybook/react-webpack5":
        optional: true
      "webpack":
        optional: true
  "@storybook/builder-manager@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/builder-webpack5@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/blocks@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/preset-react-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/cli@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-server@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/core-webpack@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "storybook@*":
    peerDependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/api@*":
    peerDependencies:
      react: "*"
      "react-dom": "*"
  "@storybook/react-webpack5@*":
    peerDependencies:
      "webpack": "*"
  "@thematic/fluent@*":
    peerDependencies:
      react-dom: "*"
      styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
