name: Python-Publish-CI
on:
  push:
    workflow_dispatch:
      branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.3.1]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        shell: bash
        working-directory: ./python/datashaper
        run: python -m poetry install

      - name: Publish to PyPi
        working-directory: ./python/datashaper
        run: |
          python -m poetry publish --build --skip-existing --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
